---
services:
  db:
    image: mariadb:10.11
    command: --event-scheduler=ON
    container_name: centralized_log_db
    networks:
      - app-network
    restart: unless-stopped
    env_file: .env
    environment:
      SERVICE_NAME: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
      - ./db/db_config.cnf:/etc/mysql/conf.d/db_config.cnf:ro
      - ./logs/db:/var/log/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${DB_USER} -p$${DB_PASSWORD}"]
      timeout: 3s
      interval: 5s
      retries: 5
      start_period: 10s

  api_collector:
    build:
      context: .
      dockerfile: api_collector/Dockerfile
    container_name: centralized_log_api
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVICE_NAME=api
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - app-network

  alerting_worker:
    build:
      context: .
      dockerfile: alerting_worker/Dockerfile
    container_name: centralized_log_worker
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVICE_NAME=worker
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ALERT_RECIPIENT=${ALERT_RECIPIENT}
      - WORKER_MAX_THREADS=${WORKER_THREADS}
      - WORKER_POLLING_INTERVAL=${WORKER_POLLING_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
      - PYTHONUNBUFFERED=1
      - DISABLE_SMTP=${DISABLE_SMTP}
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
  # for load test:
  log-client:
    build: ./tests/load_tests/client_simulator
    environment:
      - SERVICE_TYPE=client
      - REPLICA_INDEX=${REPLICA_INDEX}
    networks:
      - app-network
  # uncomment if you need start sending email to mock service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web interface (open http://localhost:8025)
      - "1025:1025"
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
